version: '2'
services:

  postgres:
    image: postgres
    container_name: book_postgres
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - /tmp/docker/book:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: book
      POSTGRES_USER: book
      POSTGRES_PASSWORD: book
