version: '2'
services:

  postgres:
    image: postgres:11
    container_name: book_postgres
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./PGDATA:/var/lib/postgresql/data
    ports:
      - 5432:5432
    command: postgres -E
    environment:
      # PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_DB: book
      POSTGRES_USER: book
      POSTGRES_PASSWORD: book
